### ISSUE TITLE
kmod::install ensure => absent no longer unloads modules.

### ISSUE THREAD

**Issue by alexjfisher** [camptocamp/puppet-kmod#29]
Hello

Is this change in behaviour intended?  In the previous version I could do...

```
kmod::install { 'usb_storage':
  ensure => absent,
}
```

and this would unload the usb_storage module.  In version 2.0.0 (even after https://github.com/camptocamp/puppet-kmod/pull/28 fix), kmod::load is no longer called.

Perhaps I should have always just be using the kmod::load type directly instead?

Thanks,
Alex

**Comment by ryayon** [comment]
Hi,

Same question here.

Regards

**Comment by raphink** [comment]
By unload, you mean remove from the conffile, or also perform an exec?

**Comment by alexjfisher** [comment]
Umm... two years ago and I've moved on... but, I think I meant the exec was no longer run.

**Comment by isandpauk** [comment]
modprobe -r <module name> is not executed when I try to unload module as described above.
