### ISSUE TITLE
Blacklisting does not actually prevent module from being loaded

### ISSUE THREAD

**Issue by gjngeldenhuis** [camptocamp/puppet-kmod#30]
When you blacklist a module it won't actually prevent you from doing a modprobe <modulename>. It was certainly my expectation that the blacklisting would not only prevent other modules from loading the blacklisted module but also prevent people from loading the module from the command line. 

My testing has been done on Red Hat Enterprise 7.1
To achieve the expected behaviour you need the following entry:
install <module name> /bin/false
in the blacklist.conf file.

I am happy to submit a pull request but wanted to discuss the existing behaviour first.

**Comment by mcanevet** [comment]
@gjngeldenhuis if this is true on every distro then +1 for a PR

**Comment by gjngeldenhuis** [comment]
@mcanevet I don't know about other distros unfortunately.

**Comment by gjngeldenhuis** [comment]
@mcanevet so a bit of an update. I have read up some more and my understanding of what blacklisting does were wrong. Blacklisting will block specified kernel module aliases. Quoting from the Red Hat man page: 
"the blacklist keyword indicates that all of that particular module's internal aliases are to be ignored."

The correct way to stop a module from loading is to do the following:
kmod::install { 'dccp': command => '/bin/false', }

So no bug, just a misunderstanding. The only small issue is that the file that gets created have an unnessarry newline entry at the top. I will submit a PR for the documentation to clarify usage and prevent others from making the same assumption as I did.

**Comment by mcanevet** [comment]
@gjngeldenhuis great! thanks!

**Comment by gjngeldenhuis** [comment]
https://github.com/camptocamp/puppet-kmod/pull/32

**Comment by mcanevet** [comment]
merged
