### ISSUE TITLE
modules does not suports multiple options

### ISSUE THREAD

**Issue by kofemann** [camptocamp/puppet-kmod#36]
HI,

we need to pass multiple options to a kernel module, but I can't achieve that as it complains about  Duplicate parameter 'option' or Duplicate declaration: Kmod::Option[nfs]:

It will be nice if one of the syntaxes where supported:

``` puppet
  kmod::option { 'nfs':
    option => 'dataserver_retrans', value => 3,
    option => 'dataserver_timeo', value => 20, 
 }
```

or

``` puppet
  kmod::option { 'nfs': option => 'dataserver_retrans', value => 3 }
  kmod::option { 'nfs': option => 'dataserver_timeo', value => 20 }
```

Thanks

**Comment by kofemann** [comment]
this is how I get it to work (which is ugly)

  kmod::option { 'pnfs-ds-retrans' : module => 'nfs', option => 'dataserver_retrans', value => 3, }
  kmod::option { 'pnfs-ds-timeo' : module => 'nfs', option => 'dataserver_timeo', value => 20, }

(and the result iin /etc/modprobe.d/nfs.conf is: ptions nfs dataserver_retrans=3 dataserver_timeo=20)

**Comment by raphink** [comment]
Why is your option with two resources ugly?

**Comment by kofemann** [comment]
while I need to specify two different resource names, but I actually want to control only one resource - nfs module.
