### ISSUE TITLE
Puppet Approved

### ISSUE THREAD

**Issue by tphoney** [camptocamp/puppet-kmod#38]
Hi,

I am reaching out to you on behalf of Puppet in regards to your Puppet Approved module camptocamp/puppet-kmod on the Puppet Forge. The Puppet Approved criteria is based on the following tenets; quality composition, reliable operation, and active development. Your module has not been updated on the Puppet Forge for over a year, are there any plans to release a new version of the module? 

There seems to be a few open pull requests that could be merged. If there has not been a new release of the module on the Puppet Forge or a response in the following 3 months, we may have to revoke your Puppet Approved status. If you are not interested in continuing maintenance of the module, you may consider contacting the open source Puppet community Vox Pupuli. They are always interested in adopting modules. There is more information here https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli.

I look forward to your response, or a new release on the Puppet Forge. 

Regards,
TP Honey
Senior Software Engineer
Puppet Modules Team

**Comment by raphink** [comment]
Hi @tphoney,

Thank you for caring about the quality of approved modules. We keep track of issues and PRs on our modules and process them regularly. There is indeed one PR on this module, and we will make sure to look into it (although I can already see that it doesn't pass tests).

**Comment by raphink** [comment]
Hi @tphoney,

I've had a look at the issues and PRs. The only PR there is has already been discussed and is not acceptable, while the issues are RFE without associated PRs.

It seems the module is simply stable and working (as the 40k+ downloads/month seem to indicate) and the quality score of the module is 5, so I don't see what would justify a new release.

**Comment by tphoney** [comment]
Those are fair points, i was not trying to attack the module. It has just such a long time since the last release. 

Thank you for the response, and apologies if i have offended. It was not the purpose of my query. 

With apologies. 
TP

**Comment by raphink** [comment]
You haven't offended at all @tphoney :smile: 

Maybe we could just update the list of supported OSes once in a while.
