### ISSUE TITLE
Add purge option

### ISSUE THREAD

**Issue by jeandoBet** [camptocamp/puppet-kmod#62]
Hi,

Could it be possible to add a purge option for the directory /etc/modprobe.d ? 

You could change your init.pp file to : 

```
class kmod (
  Optional[Hash] $list_of_aliases    = {},
  Optional[Hash] $list_of_blacklists = {},
  Optional[Hash] $list_of_installs   = {},
  Optional[Hash] $list_of_loads      = {},
  Optional[Hash] $list_of_options    = {},
  Boolean $dir_purge                 = false,
){

  file { '/etc/modprobe.d':
    ensure  => directory,
    purge   => $dir_purge,
    recurse => $dir_purge
  }
[....]
```

Declaration would give : 
```
 class { 'kmod':
    dir_purge => true
  }
```

Hope this can be implemented,
Thanks

**Comment by raphink** [comment]
Sure, that seems like a good idea.

Can you submit a PR for this please?

**Comment by jeandoBet** [comment]
Sure, but it seems I don't have the permissions to push a new branch

**Comment by raphink** [comment]
That's normal. You need to push to your fork and open a Pull Request.
